name = "app"
version = "1.0.0"
description = "williamsandholmes.com"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.6.3 and < 5.0.0"
lustre_ssg = ">= 0.8.3 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
